version: "3"

services:
  app:
    container_name: barokah-admin
    build:
      context: .
      dockerfile: Dockerfile
    image: barokah-admin
    restart: unless-stopped
    volumes:
      - ./apache.conf:/etc/apache2/sites-available/000-default.conf:ro
      - ./public/uploads:/var/www/public/uploads:rw
    ports:
      - 8000:80
    env_file:
      - .env
    extra_hosts:
      - host.docker.internal:host-gateway
